version: 2

updates:
- package-ecosystem: gomod
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: go-dep
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: npm-dep
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: gh-action
